### PR TITLE
Draft: Feature/custom banner text

### PR DESCRIPTION
**Pull request by binaryannie**
Relates to https://github.com/dotboris/prod-guard/issues/141

### CODE REVIEW

**Comment by binaryannie** [comment]
@dotboris I'd like your opinion on something. I want to make the text input available only on warning styles that have a text (not border). I was think of changing the code in warning-styles.js to look more like that:

```js
export const names = {
  topBanner: {
    label: 'Top Banner',
    hasText: true
  },
  bottomBanner: {
    label: 'Bottom Banner',
    hasText: true
  },
  border: {
    label: 'Border',
    hasText: false
  }
}
```
Obviously, I'd have to find another name then `names` for the export as it's clearly not just that anymore. It could then be expanded to have different possible config for different warning styles. 

Comments?

**Comment by dotboris** [comment]
@binaryannie I would prefer if you did an `if` on `this.warningStyle` in instead of defining and using the `hasText` field in `site-form.jsx`.

I've read through the code and it seems like `hasText` is only used inside of `site-form.jsx`. Having it defined somewhere else creates a low cohesion + high coupling scenario which I would like to avoid.

I think that it might be too early to extract a sort of definitions of the styles like this. My vision is that this project will eventually let you customize more than the text. It could be the color, font size, etc. I'm not sure if the pattern of `has{Field}` is going to work when that comes around. I'm also not sure how it's going to hold up when we add new styles. I think that making a generic solution for that that is best handled when complexity rises.

Thank you for your effort and contribution. I really appreciate the help.

**Comment by binaryannie** [comment]
Thanks for the feedback! Will update and let you know when I'm done!

**Comment by dotboris** [comment]
@binaryannie The project has switched from using Travis CI to Github actions. I suggest that you sync your branch with master so that the CI works in this PR.

**Comment by dotboris** [comment]
@binaryannie I've implemented the feature you requested in #141 with #384 . #384 effectively implements what this PR has started to implement. To avoid clutter in the repo, I'm going to close this PR. If you want to improve the feature, feel free to start a new PR or re-open this one.

**Pull request closed without merging**
